const CONFIGS = {
  DOMAIN: process.env.NEXT_PUBLIC_DOMAIN,
  RESIZE_IMAGE: process.env.NEXT_PUBLIC_RESIZE_IMAGE, // NEXTJS | CLOUDFLARE | NONE
  MEDIA_BASE: process.env.NEXT_PUBLIC_MEDIA_BASE,
  GRPC_SERVER: process.env.NEXT_PUBLIC_GRPC_SERVER,
  USE_INTERNAL_DOMAIN: process.env.NEXT_PUBLIC_USE_INTERNAL_DOMAIN,
}

export default CONFIGS
